name: Publish

on:
  push:
    # Publish `v*` tags as releases.
    tags:
    - v*
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: bloomberg/goldpinger
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: simple
      - name: Build and push vendor
        id: docker_build_vendor
        uses: docker/build-push-action@v2
        with:
          context: .
          flavor: |
            suffix: -vendor,onlatest=false
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}-vendor
          labels: ${{ steps.meta.outputs.labels }}
          target: vendor
